# Generated by Django 5.1.6 on 2025-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydroponics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.CharField(
                choices=[("PH", "pH"), ("TEMP", "Temperatura"), ("TDS", "TDS")],
                help_text="Wybierz typ czujnika",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="SensorType",
        ),
    ]
