# Generated by Django 5.1.6 on 2025-02-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydroponics", "0002_alter_sensor_sensor_type_delete_sensortype"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="sensor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="hydroponics.sensor",
            ),
            preserve_default=False,
        ),
    ]
