# Generated by Django 5.1.6 on 2025-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydroponics", "0003_measurement_sensor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="ph",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="tds",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="temperature",
        ),
        migrations.AddField(
            model_name="measurement",
            name="value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
