# Generated by Django 5.1.6 on 2025-02-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hydroponics", "0004_remove_measurement_ph_remove_measurement_tds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="system",
        ),
    ]
