# Generated by Django 5.1.6 on 2025-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydroponics", "0005_remove_measurement_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.CharField(
                choices=[("PH", "pH"), ("TEMP", "Temperature"), ("TDS", "TDS")],
                help_text="Choose sensor type.",
                max_length=10,
            ),
        ),
    ]
